[package]
name = "gc-arena"
version = "0.1.0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"
license = "MIT OR CC0"
repository = "https://github.com/kyren/gc-arena"

[dependencies]
gc-arena-derive = { path = "../gc-arena-derive", version = "0.1" }

[dev-dependencies]
rand = "0.5"
